services:
  # PostgreSQL Database
  - type: pserv
    name: pasteforge-db
    env: node
    plan: free
    databaseName: pasteforge
    databaseUser: pasteforge_user

  # Backend API Service
  - type: web
    name: pasteforge-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: pasteforge-db
          property: connectionString
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: static
    name: pasteforge-frontend
    env: static
    plan: free
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://pasteforge-api.onrender.com/api